<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-06-27 12:37
=======
# Generated by Django 6.0.5 on 2026-06-28 04:00
>>>>>>> 54194a816ee17a2c35614a60840ec2fdb40efe02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='TestBack.department')),
=======
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학기 명칭 (예: 2026년 1학기)', max_length=20, unique=True)),
>>>>>>> 54194a816ee17a2c35614a60840ec2fdb40efe02
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='TestBack.course')),
=======
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='TestBack.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='TestBack.department')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='TestBack.professor')),
                ('semesters', models.ManyToManyField(blank=True, help_text='개설된 수강 학기 목록', related_name='courses', to='TestBack.semester')),
>>>>>>> 54194a816ee17a2c35614a60840ec2fdb40efe02
            ],
        ),
        migrations.CreateModel(
            name='ExamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('semester', models.CharField(max_length=20)),
=======
>>>>>>> 54194a816ee17a2c35614a60840ec2fdb40efe02
                ('difficulty', models.IntegerField()),
                ('exam_info', models.TextField(max_length=500)),
                ('exam_type', models.CharField(choices=[('객관식', '객관식'), ('단답형', '단답형'), ('서술형', '서술형'), ('논술형', '논술형'), ('코딩/실습', '코딩/실습'), ('기타', '기타')], max_length=20)),
                ('review', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestBack.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestBack.department')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestBack.professor')),
<<<<<<< HEAD
=======
                ('semester', models.ForeignKey(help_text='수강 학기', on_delete=django.db.models.deletion.PROTECT, related_name='exam_reviews', to='TestBack.semester')),
>>>>>>> 54194a816ee17a2c35614a60840ec2fdb40efe02
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(help_text='시험 종류 (중간/기말 등)', max_length=20)),
                ('test_format', models.CharField(help_text='시험 유형 (객관식/주관식 등)', max_length=50)),
                ('rating', models.PositiveIntegerField(default=3, help_text='난이도 별점 (1~5)')),
                ('title', models.CharField(help_text='후기 제목', max_length=200)),
                ('content', models.TextField(help_text='총평 및 내용')),
                ('views', models.PositiveIntegerField(default=0, help_text='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일시')),
<<<<<<< HEAD
                ('course', models.ForeignKey(help_text='대상 과목 선택', on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='TestBack.course')),
                ('likes', models.ManyToManyField(blank=True, help_text='좋아요 누른 유저들', related_name='liked_tests', to=settings.AUTH_USER_MODEL)),
                ('scraps', models.ManyToManyField(blank=True, help_text='스크랩한 유저들', related_name='scrapped_tests', to=settings.AUTH_USER_MODEL)),
=======
                ('course', models.ForeignKey(help_text='대상 과목', on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='TestBack.course')),
                ('department', models.ForeignKey(blank=True, help_text='학과', null=True, on_delete=django.db.models.deletion.PROTECT, to='TestBack.department')),
                ('likes', models.ManyToManyField(blank=True, help_text='좋아요 누른 유저들', related_name='liked_tests', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(blank=True, help_text='교수', null=True, on_delete=django.db.models.deletion.PROTECT, to='TestBack.professor')),
                ('scraps', models.ManyToManyField(blank=True, help_text='스크랩한 유저들', related_name='scrapped_tests', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, help_text='시험 치른 학기', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='TestBack.semester')),
>>>>>>> 54194a816ee17a2c35614a60840ec2fdb40efe02
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='TestBack.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TestBack.test')),
            ],
        ),
    ]
