# Generated by Django 6.0.5 on 2026-06-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestBack", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="exam_info",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tests",
                to="TestBack.course",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="TestBack.department",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="exam_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="test",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_tests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="TestBack.professor",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="rating",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="test",
            name="scraps",
            field=models.ManyToManyField(
                blank=True, related_name="scrapped_tests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tests",
                to="TestBack.semester",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_format",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="test",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
