# Generated by Django 6.0.5 on 2026-06-28 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TestBack",
            "0002_test_exam_info_alter_test_content_alter_test_course_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="test",
            constraint=models.UniqueConstraint(
                fields=("user", "course"), name="unique_user_course_review"
            ),
        ),
    ]
