# Generated by Django 6.0.5 on 2026-07-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestBack", "0003_test_unique_user_course_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="exam_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_format",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
