# Generated by Django 6.0.5 on 2026-07-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TestBack", "0004_alter_test_exam_type_alter_test_test_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="exam_type",
        ),
        migrations.RemoveField(
            model_name="test",
            name="test_format",
        ),
    ]
